hero_image: images/banner.png
theme: red
duration: 1
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Against the Clock
description: Make a timer and use it to challenge your friends.
original_url: https://codeclubprojects.org/en-GB/microbit/against-the-clock
interests: ''
technologies: ''
site_areas: codeclub, microbit
steps:
- title: Introduction
- title: Setting up your timer
- title: Starting and stopping your timer
- title: 'Challenge: Counting Down'

