---
hero_image: images/against-the-clock.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: सबसे तेज़ करना
description: एक टाइमर बनाएँ और अपने दोस्तों को चुनौती देने के लिए इसका उपयोग करें।
original_url: https://codeclubprojects.org/en-GB/microbit/against-the-clock
interests: games
technologies: microbit
site_areas: projects
hardware: microbit
software: ''
version: 3.0.1
last_tested: 2019-02-28
steps:
- title: परिचय
  completion: engaged
- title: अपना टाइमर सेट अप करना
- title: अपने टाइमर को शुरू करना और रोकना
  completion: internal
- title: 'चुनौती: काउंट डाउन करना'
