---
hero_image: images/against-the-clock.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Yn erbyn y Cloc
description: Gwnewch amserydd a'i ddefnyddio i herio'ch ffrindiau.
original_url: https://codeclubprojects.org/en-GB/microbit/against-the-clock
interests: games
technologies: microbit
site_areas: projects
hardware: microbit
software: ''
version: 3
last_tested: 2017-01-01
steps:
- title: Cyflwyniad
  completion: engaged
- title: Gosod eich amserydd
- title: Dechrau a stopio eich amserydd
  completion: internal
- title: 'Her: Cyfrif i lawr'
