---
hero_image: images/against-the-clock.png
theme: glaswyrdd
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Yn erbyn y Cloc
description: Gwnewch amserydd a'i ddefnyddio i herio'ch ffrindiau.
original_url: https://codeclubprojects.org/en-GB/microbit/against-the-clock
interests: gemau
technologies: microbit
site_areas: prosiectau
hardware: microbit
software: ''
version: 3.0.1
last_tested: 2019-02-28
steps:
  - 
    title: Cyflwyniad
  - 
    title: Gosod eich amserydd
  - 
    title: Dechrau a stopio'ch amserydd
    completion:
      - engaged
      - internal
  - 
    title: 'Her: Cyfrif i lawr'
