---
hero_image: images/against-the-clock.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Gegen die Uhr
description: Erstelle einen Timer und nutze ihn um deine Freunde herauszufordern.
original_url: https://codeclubprojects.org/en-GB/microbit/against-the-clock
interests: games
technologies: microbit
site_areas: projects
hardware: microbit
software: ''
version: 3.0.1
last_tested: 2019-02-28
steps:
- title: Einleitung
  completion: engaged
- title: Timer einstellen
- title: Timer starten und anhalten
  completion: internal
- title: 'Herausforderung: Herunterzählen'
