---
hero_image: images/against-the-clock.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programmering-1, phys-comp-0, tillverkning-0, community-0
title: Against the Clock
description: Make a timer and use it to challenge your friends.
original_url: https://codeclubprojects.org/en-GB/microbit/against-the-clock
interests: spel
technologies: microbit
site_areas: projekt
hardware: microbit
software: ''
version: 3.0.1
last_tested: 2019-02-28
steps:
  - 
    title: Introduktion
  - 
    title: Setting up your timer
  - 
    title: Starting and stopping your timer
  - 
    title: 'Challenge: Counting Down'
