---
hero_image: images/against-the-clock.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programmation-1, phys-comp-0, fabrication-0, communauté-0
title: Contre la Montre
description: Construis un chronomètre et utilise le pour défier tes amis.
original_url: https://codeclubprojects.org/en-GB/microbit/against-the-clock
interests: games
technologies: microbit
site_areas: projets
hardware: microbit
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introduction
  - 
    title: Configurer ton chronomètre
  - 
    title: Démarrer et arrêter ton chronomètre
  - 
    title: 'Défi : Compte à Rebours'
