---
hero_image: images / against-the-clock.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, tasarım-0, programlama-1, phys-comp-0, üretim-0, topluluk-0
title: Against the Clock
description: Make a timer and use it to challenge your friends.
original_url: https://codeclubprojects.org/en-GB/microbit/against-the-clock
interests: oyunlar
technologies: microbit
site_areas: projects
hardware: microbit
software: ''
version: 3.0.1
last_tested: 2019-02-28
steps:
  - 
    title: Giriş
  - 
    title: Setting up your timer
  - 
    title: Starting and stopping your timer
  - 
    title: 'Challenge: Counting Down'
